### ISSUE TITLE
Certificates for Sitecore 90x are expired

### ISSUE THREAD

**Issue by fpodshivadlov** [asmagin/sitecore-packer#24]
The certificates under `\src\components\sitecore\chef\cookbooks\scp_sitecore_90x\files\default\certificates\` are expired.

**Comment by asmagin** [comment]
@outruller have you regenerated passwords in your recent fixes?

**Comment by outruller** [comment]
@asmagin 
Nope, for boxes with sitecore 9.0.x I've used certificates that were there initially.
For sitecore 9.1.x boxes we use another root certificate.
I think that It might be better to have same root cert thru all boxes, so now I incline to replace old 9.0+ certificates with newly generated from root cert used in 9.1.x boxes.
What you think?

**Comment by asmagin** [comment]
I agree that we should use the same certificates for all images. 
@fpodshivadlov, The only problem for you is that you will need to change the image.

**Comment by fpodshivadlov** [comment]
That's ok, thank you. In case if someone needs to preserve the old box, the certificates can be regenerated and updated manually.
How long will the new certificates be valid?
