### ISSUE TITLE
Remote debugger 2019 is missing

### ISSUE THREAD

**Issue by FatkullinT** [asmagin/sitecore-packer#25]
Today actual version of the Visual Studio is 2019, but remote debugger installed only for 2017.

**Comment by outruller** [comment]
Hi!

As far as my understanding goes remote debugger for VS2019 is not backward compatible with previous versions.
I suspect that we might install both alongside (for <=2017 and for >=2019) but it should be tested first.

Meanwhile as a workaround, if your work requires VS2019 you may grab an existing box, install and configure remote debugger for VS2019 manually (or any other tools you want) and repack it using [Vagrant](https://www.vagrantup.com/docs/cli/package.html).

Thanks!

**Comment by asmagin** [comment]
The remote debugger was added by @akuryan 
Please, check if it works for you.
