### ISSUE TITLE
Windows update not running and unable to RDP

### ISSUE THREAD

**Issue by zkniebel** [asmagin/sitecore-packer#9]
I'm getting an RDP error “The function requested is not supported” when trying to RDP into the machine. From some online reading, it sounds like this is due to a missing Windows Update. Packer is supposed to have the updates on it, but it appears that my (new) computer may have an update missing from the image. See this post for more (info repeated below): https://serverfault.com/a/913790

> If your target server is Windows Server 2016, the first package from [this list](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4103723) (2018-05 Cumulative Update for Windows Server 2016 for x64-based Systems (KB4103723)) worked for me:
>
> Download and Install on target server
> Restart
> As already mentioned, this is the recommended way and does not require any other changes on source machines.
>
> For Windows Server 2012 R2 the package 2018-05 Security Only Quality Update for Windows Server 2012 R2 for x64-based Systems (KB4103715) from [here](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4103715) solved the issue.

Additionally, the Virtual Box had the Windows Update service disabled by default. This should be enabled by default, otherwise users cannot install updates.

**Comment by asmagin** [comment]
Please, check this URL for mitigation:
https://support.microsoft.com/en-us/help/4295591/credssp-encryption-oracle-remediation-error-when-to-rdp-to-azure-vm
